version: "3"

services:
  fuseki:
    image: ghcr.io/zazuko/fuseki-geosparql:v3.3.0
    ports:
      - 3030:3030
    environment:
      - ADMIN_PASSWORD=secret
    volumes:
      - ./datasets/fuseki-geosparql/data.nt:/data/data.nt:ro
      - ./datasets/fuseki-geosparql/config.ttl:/fuseki/config.ttl:ro
